set -g default-terminal "tmux-256color"
set -ga terminal-features ",xterm-256color:RGB"

set -g mouse on
set -g set-clipboard on

set -g base-index 1
set -g renumber-windows on
set -g status-position bottom

set-window-option -g mode-keys vi

set -g default-shell /usr/bin/zsh
set -g default-command /usr/bin/zsh
set -g update-environment "DISPLAY SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY PATH"

# Prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Reload config
bind r source-file ~/.tmux.conf \; display-message "tmux reloaded"

# Session / window navigation
bind s choose-session
bind w choose-window
bind -r ^ last-window

# Vim-like pane movement
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Pane resizing
bind -r M-h resize-pane -L 5
bind -r M-l resize-pane -R 5
bind -r M-k resize-pane -U 5
bind -r M-j resize-pane -D 5

#### PLUGINS ####

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @plugin 'niksingh710/minimal-tmux-status'

# Continuum
set -g @continuum-save-interval '15'
set -g @continuum-restore 'on'

set-environment -g PATH "/usr/local/bin:/bin:/usr/bin"

### Theme

# Base
set -g status on
set -g status-style "bg=#1d2021,fg=#ebdbb2"
set -g status-interval 5
set -g status-justify left

# Left: session name
set -g status-left-length 25
# set -g status-left "#[fg=#83a598,bold]#S #[fg=#3c3836]│ "
set -g status-left "#[fg=#8ec07c,bold]#S#{?window_zoomed_flag, #[fg=#fabd2f]⛶,} #[fg=#3c3836]│ "

# Right: empty
set -g status-right ""
set -g status-right-length 0

# Separator between windows
set -g window-status-separator " #[fg=#3c3836]│ "

# Inactive windows
set -g window-status-style "fg=#a89984,bg=#1d2021"
set -g window-status-format " #I:#W "

# Active window 
set -g window-status-current-style "fg=#1d2021,bg=#fabd2f,bold"
set -g window-status-current-format " #I:#W "

# Needs to be at the bottom
run '~/.tmux/plugins/tpm/tpm'
